# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128, verbose_name='Aktenzeichen')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.File', verbose_name='Akte')),
                ('timer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_timer.Timer')),
            ],
        ),
    ]
