# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_timer', '0002_timer_user'),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_timer.Timer'),
        ),
    ]
