# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20180104_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='billable',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Abrechenbare Zeit'),
        ),
    ]
