# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_task_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='min_billable_time',
            field=models.DurationField(default=datetime.timedelta(0, 900), verbose_name='kleinste Zeiteinheit'),
        ),
    ]
