# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_task_min_billable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='billable',
            field=models.DurationField(null=True, verbose_name='Abrechenbare Zeit'),
        ),
    ]
